-- Tablas y catalogos de notificaciones para el esquema en espanol.

CREATE TABLE IF NOT EXISTS tipos_notificacion (
    codigo VARCHAR(40) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS canales_notificacion (
    codigo VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS estados_entrega (
    codigo VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    es_final BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_destinatario_id BIGINT NOT NULL
        REFERENCES usuarios(id) ON DELETE CASCADE,
    codigo_tipo VARCHAR(40) NOT NULL
        REFERENCES tipos_notificacion(codigo) ON DELETE RESTRICT,
    postulacion_id BIGINT
        REFERENCES postulaciones(id) ON DELETE CASCADE,
    entrevista_id BIGINT
        REFERENCES entrevistas(id) ON DELETE CASCADE,
    titulo VARCHAR(180) NOT NULL,
    mensaje TEXT NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    leido_en TIMESTAMPTZ,
    CONSTRAINT verifica_notificacion_lectura
        CHECK (leido_en IS NULL OR leido_en >= creado_en)
);

CREATE TABLE IF NOT EXISTS entregas_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificacion_id BIGINT NOT NULL
        REFERENCES notificaciones(id) ON DELETE CASCADE,
    codigo_canal VARCHAR(20) NOT NULL
        REFERENCES canales_notificacion(codigo) ON DELETE RESTRICT,
    codigo_estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        REFERENCES estados_entrega(codigo) ON DELETE RESTRICT,
    direccion_destino VARCHAR(320),
    programado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    enviado_en TIMESTAMPTZ,
    id_mensaje_proveedor VARCHAR(255),
    CONSTRAINT unico_entrega_notificacion_canal
        UNIQUE (notificacion_id, codigo_canal),
    CONSTRAINT verifica_entrega_enviada
        CHECK (enviado_en IS NULL OR enviado_en >= programado_en)
);

CREATE TABLE IF NOT EXISTS intentos_entrega_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrega_id BIGINT NOT NULL
        REFERENCES entregas_notificacion(id) ON DELETE CASCADE,
    intentado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    exitoso BOOLEAN NOT NULL,
    mensaje_error TEXT
);

INSERT INTO tipos_notificacion (codigo, nombre) VALUES
    ('CONFIRMACION_POSTULACION', 'Confirmación de postulación'),
    ('CAMBIO_ESTADO', 'Cambio de estado'),
    ('INVITACION_ENTREVISTA', 'Invitación a entrevista')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre;

INSERT INTO canales_notificacion (codigo, nombre) VALUES
    ('APLICACION', 'Aplicación'),
    ('CORREO', 'Correo electrónico')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre;

INSERT INTO estados_entrega (codigo, nombre, es_final) VALUES
    ('PENDIENTE', 'Pendiente', FALSE),
    ('PROCESANDO', 'Procesando', FALSE),
    ('ENVIADO', 'Enviado', TRUE),
    ('FALLIDO', 'Fallido', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    es_final = EXCLUDED.es_final;

CREATE INDEX IF NOT EXISTS indice_notificaciones_usuario_fecha
    ON notificaciones(usuario_destinatario_id, creado_en DESC);

CREATE INDEX IF NOT EXISTS indice_notificaciones_no_leidas
    ON notificaciones(usuario_destinatario_id, creado_en DESC)
    WHERE leido_en IS NULL;

CREATE INDEX IF NOT EXISTS indice_notificaciones_postulacion
    ON notificaciones(postulacion_id)
    WHERE postulacion_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS indice_notificaciones_entrevista
    ON notificaciones(entrevista_id)
    WHERE entrevista_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS indice_entregas_estado_programacion
    ON entregas_notificacion(codigo_estado, programado_en);

CREATE INDEX IF NOT EXISTS indice_intentos_entrega_fecha
    ON intentos_entrega_notificacion(entrega_id, intentado_en DESC);
