-- Completa las tablas de reclutamiento que no formaban parte de la base inicial.

CREATE TABLE IF NOT EXISTS perfiles_personal (
    usuario_id BIGINT PRIMARY KEY
        REFERENCES usuarios(id) ON DELETE CASCADE,
    departamento_id BIGINT
        REFERENCES departamentos(id) ON DELETE SET NULL,
    cargo VARCHAR(120),
    telefono VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS historial_estados_plaza (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plaza_id BIGINT NOT NULL
        REFERENCES plazas(id) ON DELETE CASCADE,
    codigo_estado_anterior VARCHAR(20)
        REFERENCES estados_plaza(codigo) ON DELETE RESTRICT,
    codigo_estado_nuevo VARCHAR(20) NOT NULL
        REFERENCES estados_plaza(codigo) ON DELETE RESTRICT,
    cambiado_por_id BIGINT NOT NULL
        REFERENCES usuarios(id) ON DELETE RESTRICT,
    motivo TEXT,
    cambiado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT verifica_historial_plaza_estado
        CHECK (
            codigo_estado_anterior IS NULL
            OR codigo_estado_anterior <> codigo_estado_nuevo
        )
);

CREATE TABLE IF NOT EXISTS tipos_requisito (
    codigo VARCHAR(30) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requisitos_plaza (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plaza_id BIGINT NOT NULL
        REFERENCES plazas(id) ON DELETE CASCADE,
    codigo_tipo VARCHAR(30) NOT NULL
        REFERENCES tipos_requisito(codigo) ON DELETE RESTRICT,
    descripcion TEXT,
    obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
    peso NUMERIC(5,2) NOT NULL
        CHECK (peso > 0 AND peso <= 100),
    orden_visualizacion SMALLINT NOT NULL DEFAULT 1
        CHECK (orden_visualizacion > 0),
    CONSTRAINT unico_requisito_plaza_orden
        UNIQUE (plaza_id, orden_visualizacion)
);

CREATE TABLE IF NOT EXISTS requisitos_habilidad (
    requisito_id BIGINT PRIMARY KEY
        REFERENCES requisitos_plaza(id) ON DELETE CASCADE,
    habilidad_id BIGINT NOT NULL
        REFERENCES habilidades(id) ON DELETE RESTRICT,
    nivel_habilidad_minimo_id BIGINT
        REFERENCES niveles_habilidad(id) ON DELETE RESTRICT,
    anios_minimos NUMERIC(4,1)
        CHECK (anios_minimos >= 0)
);

CREATE TABLE IF NOT EXISTS requisitos_idioma (
    requisito_id BIGINT PRIMARY KEY
        REFERENCES requisitos_plaza(id) ON DELETE CASCADE,
    idioma_id BIGINT NOT NULL
        REFERENCES idiomas(id) ON DELETE RESTRICT,
    nivel_idioma_minimo_id BIGINT NOT NULL
        REFERENCES niveles_idioma(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS requisitos_certificacion (
    requisito_id BIGINT PRIMARY KEY
        REFERENCES requisitos_plaza(id) ON DELETE CASCADE,
    certificacion_id BIGINT NOT NULL
        REFERENCES certificaciones(id) ON DELETE RESTRICT,
    debe_estar_vigente BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS requisitos_educacion (
    requisito_id BIGINT PRIMARY KEY
        REFERENCES requisitos_plaza(id) ON DELETE CASCADE,
    nivel_educativo_minimo_id BIGINT NOT NULL
        REFERENCES niveles_educativos(id) ON DELETE RESTRICT,
    area_estudio_id BIGINT
        REFERENCES areas_estudio(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS requisitos_experiencia (
    requisito_id BIGINT PRIMARY KEY
        REFERENCES requisitos_plaza(id) ON DELETE CASCADE,
    profesion_id BIGINT
        REFERENCES profesiones(id) ON DELETE RESTRICT,
    meses_minimos INTEGER NOT NULL
        CHECK (meses_minimos >= 0)
);

CREATE TABLE IF NOT EXISTS requisitos_disponibilidad (
    requisito_id BIGINT PRIMARY KEY
        REFERENCES requisitos_plaza(id) ON DELETE CASCADE,
    requerido_desde DATE,
    requiere_reubicacion BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_viajar BOOLEAN NOT NULL DEFAULT FALSE,
    descripcion_horario VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS modelos_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor VARCHAR(100) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    version VARCHAR(80) NOT NULL,
    CONSTRAINT unico_modelo_ia_version
        UNIQUE (proveedor, nombre, version)
);

CREATE TABLE IF NOT EXISTS motores_analisis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_ia_id BIGINT
        REFERENCES modelos_ia(id) ON DELETE RESTRICT,
    nombre VARCHAR(120) NOT NULL,
    version VARCHAR(80) NOT NULL,
    version_instruccion VARCHAR(80),
    CONSTRAINT unico_motor_analisis_version
        UNIQUE (nombre, version, version_instruccion)
);

CREATE TABLE IF NOT EXISTS estados_procesamiento (
    codigo VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    es_final BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS analisis_cv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculo_id BIGINT NOT NULL
        REFERENCES curriculos(id) ON DELETE CASCADE,
    motor_analisis_id BIGINT NOT NULL
        REFERENCES motores_analisis(id) ON DELETE RESTRICT,
    codigo_estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        REFERENCES estados_procesamiento(codigo) ON DELETE RESTRICT,
    texto_extraido TEXT,
    resumen_profesional TEXT,
    meses_experiencia_calculados INTEGER
        CHECK (meses_experiencia_calculados >= 0),
    iniciado_en TIMESTAMPTZ,
    completado_en TIMESTAMPTZ,
    mensaje_error TEXT,
    vigente BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT verifica_analisis_cv_fechas
        CHECK (
            completado_en IS NULL
            OR iniciado_en IS NULL
            OR completado_en >= iniciado_en
        )
);

CREATE TABLE IF NOT EXISTS datos_personales_analisis_cv (
    analisis_id BIGINT PRIMARY KEY
        REFERENCES analisis_cv(id) ON DELETE CASCADE,
    nombre_completo VARCHAR(200),
    correo VARCHAR(254),
    telefono VARCHAR(30),
    profesion_texto VARCHAR(180),
    ciudad_texto VARCHAR(180)
);

CREATE TABLE IF NOT EXISTS experiencias_analisis_cv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analisis_id BIGINT NOT NULL
        REFERENCES analisis_cv(id) ON DELETE CASCADE,
    profesion_id BIGINT
        REFERENCES profesiones(id) ON DELETE SET NULL,
    empresa VARCHAR(180),
    puesto VARCHAR(180) NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    descripcion TEXT,
    confianza NUMERIC(5,4)
        CHECK (confianza >= 0 AND confianza <= 1),
    CONSTRAINT verifica_experiencia_analisis_fechas
        CHECK (
            fecha_fin IS NULL
            OR fecha_inicio IS NULL
            OR fecha_fin >= fecha_inicio
        )
);

CREATE TABLE IF NOT EXISTS educaciones_analisis_cv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analisis_id BIGINT NOT NULL
        REFERENCES analisis_cv(id) ON DELETE CASCADE,
    institucion_texto VARCHAR(180) NOT NULL,
    nivel_educativo_id BIGINT
        REFERENCES niveles_educativos(id) ON DELETE SET NULL,
    area_estudio_id BIGINT
        REFERENCES areas_estudio(id) ON DELETE SET NULL,
    titulo_obtenido VARCHAR(180),
    fecha_inicio DATE,
    fecha_fin DATE,
    confianza NUMERIC(5,4)
        CHECK (confianza >= 0 AND confianza <= 1),
    CONSTRAINT verifica_educacion_analisis_fechas
        CHECK (
            fecha_fin IS NULL
            OR fecha_inicio IS NULL
            OR fecha_fin >= fecha_inicio
        )
);

CREATE TABLE IF NOT EXISTS habilidades_analisis_cv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analisis_id BIGINT NOT NULL
        REFERENCES analisis_cv(id) ON DELETE CASCADE,
    habilidad_id BIGINT
        REFERENCES habilidades(id) ON DELETE SET NULL,
    nombre_detectado VARCHAR(150) NOT NULL,
    confianza NUMERIC(5,4)
        CHECK (confianza >= 0 AND confianza <= 1),
    evidencia TEXT,
    CONSTRAINT unico_habilidad_analisis_nombre
        UNIQUE (analisis_id, nombre_detectado)
);

CREATE TABLE IF NOT EXISTS idiomas_analisis_cv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analisis_id BIGINT NOT NULL
        REFERENCES analisis_cv(id) ON DELETE CASCADE,
    idioma_id BIGINT
        REFERENCES idiomas(id) ON DELETE SET NULL,
    nombre_detectado VARCHAR(80) NOT NULL,
    nivel_idioma_id BIGINT
        REFERENCES niveles_idioma(id) ON DELETE SET NULL,
    confianza NUMERIC(5,4)
        CHECK (confianza >= 0 AND confianza <= 1),
    CONSTRAINT unico_idioma_analisis_nombre
        UNIQUE (analisis_id, nombre_detectado)
);

CREATE TABLE IF NOT EXISTS certificaciones_analisis_cv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analisis_id BIGINT NOT NULL
        REFERENCES analisis_cv(id) ON DELETE CASCADE,
    certificacion_id BIGINT
        REFERENCES certificaciones(id) ON DELETE SET NULL,
    nombre_detectado VARCHAR(180) NOT NULL,
    emitida_en DATE,
    vence_en DATE,
    confianza NUMERIC(5,4)
        CHECK (confianza >= 0 AND confianza <= 1),
    CONSTRAINT verifica_certificacion_analisis_fechas
        CHECK (
            vence_en IS NULL
            OR emitida_en IS NULL
            OR vence_en >= emitida_en
        ),
    CONSTRAINT unico_certificacion_analisis_nombre
        UNIQUE (analisis_id, nombre_detectado)
);

CREATE TABLE IF NOT EXISTS evaluaciones_postulacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id BIGINT NOT NULL
        REFERENCES postulaciones(id) ON DELETE CASCADE,
    analisis_cv_id BIGINT NOT NULL
        REFERENCES analisis_cv(id) ON DELETE RESTRICT,
    motor_analisis_id BIGINT NOT NULL
        REFERENCES motores_analisis(id) ON DELETE RESTRICT,
    codigo_estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        REFERENCES estados_procesamiento(codigo) ON DELETE RESTRICT,
    porcentaje_compatibilidad NUMERIC(5,2)
        CHECK (
            porcentaje_compatibilidad IS NULL
            OR (
                porcentaje_compatibilidad >= 0
                AND porcentaje_compatibilidad <= 100
            )
        ),
    fortalezas TEXT,
    recomendaciones_mejora TEXT,
    iniciado_en TIMESTAMPTZ,
    completado_en TIMESTAMPTZ,
    mensaje_error TEXT,
    vigente BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT verifica_evaluacion_fechas
        CHECK (
            completado_en IS NULL
            OR iniciado_en IS NULL
            OR completado_en >= iniciado_en
        )
);

CREATE TABLE IF NOT EXISTS resultados_requisitos_evaluacion (
    evaluacion_id BIGINT NOT NULL
        REFERENCES evaluaciones_postulacion(id) ON DELETE CASCADE,
    requisito_id BIGINT NOT NULL
        REFERENCES requisitos_plaza(id) ON DELETE RESTRICT,
    cumplido BOOLEAN NOT NULL,
    porcentaje_puntuacion NUMERIC(5,2) NOT NULL
        CHECK (porcentaje_puntuacion >= 0 AND porcentaje_puntuacion <= 100),
    evidencia TEXT,
    explicacion TEXT,
    PRIMARY KEY (evaluacion_id, requisito_id)
);

INSERT INTO estados_procesamiento (codigo, nombre, es_final) VALUES
    ('PENDIENTE', 'Pendiente', FALSE),
    ('PROCESANDO', 'Procesando', FALSE),
    ('COMPLETADO', 'Completado', TRUE),
    ('FALLIDO', 'Fallido', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    es_final = EXCLUDED.es_final;

INSERT INTO tipos_requisito (codigo, nombre) VALUES
    ('HABILIDAD', 'Habilidad'),
    ('IDIOMA', 'Idioma'),
    ('CERTIFICACION', 'Certificación'),
    ('EDUCACION', 'Educación'),
    ('EXPERIENCIA', 'Experiencia'),
    ('DISPONIBILIDAD', 'Disponibilidad')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre;

CREATE INDEX IF NOT EXISTS indice_perfiles_personal_departamento
    ON perfiles_personal(departamento_id);

CREATE INDEX IF NOT EXISTS indice_historial_plaza_fecha
    ON historial_estados_plaza(plaza_id, cambiado_en DESC);

CREATE INDEX IF NOT EXISTS indice_historial_plaza_usuario
    ON historial_estados_plaza(cambiado_por_id);

CREATE INDEX IF NOT EXISTS indice_requisitos_plaza
    ON requisitos_plaza(plaza_id);

CREATE INDEX IF NOT EXISTS indice_requisitos_tipo
    ON requisitos_plaza(codigo_tipo);

CREATE INDEX IF NOT EXISTS indice_requisitos_habilidad
    ON requisitos_habilidad(habilidad_id);

CREATE INDEX IF NOT EXISTS indice_requisitos_idioma
    ON requisitos_idioma(idioma_id);

CREATE INDEX IF NOT EXISTS indice_requisitos_certificacion
    ON requisitos_certificacion(certificacion_id);

CREATE INDEX IF NOT EXISTS indice_requisitos_educacion_nivel
    ON requisitos_educacion(nivel_educativo_minimo_id);

CREATE INDEX IF NOT EXISTS indice_requisitos_experiencia_profesion
    ON requisitos_experiencia(profesion_id);

CREATE INDEX IF NOT EXISTS indice_motores_analisis_modelo
    ON motores_analisis(modelo_ia_id);

CREATE INDEX IF NOT EXISTS indice_analisis_curriculo_fecha
    ON analisis_cv(curriculo_id, creado_en DESC);

CREATE INDEX IF NOT EXISTS indice_analisis_motor
    ON analisis_cv(motor_analisis_id);

CREATE UNIQUE INDEX IF NOT EXISTS indice_analisis_vigente_curriculo
    ON analisis_cv(curriculo_id)
    WHERE vigente;

CREATE INDEX IF NOT EXISTS indice_experiencias_analisis
    ON experiencias_analisis_cv(analisis_id);

CREATE INDEX IF NOT EXISTS indice_experiencias_profesion
    ON experiencias_analisis_cv(profesion_id);

CREATE INDEX IF NOT EXISTS indice_educaciones_analisis
    ON educaciones_analisis_cv(analisis_id);

CREATE INDEX IF NOT EXISTS indice_habilidades_analisis
    ON habilidades_analisis_cv(analisis_id);

CREATE INDEX IF NOT EXISTS indice_habilidades_catalogo_analisis
    ON habilidades_analisis_cv(habilidad_id)
    WHERE habilidad_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS indice_idiomas_analisis
    ON idiomas_analisis_cv(analisis_id);

CREATE INDEX IF NOT EXISTS indice_certificaciones_analisis
    ON certificaciones_analisis_cv(analisis_id);

CREATE INDEX IF NOT EXISTS indice_evaluaciones_postulacion_fecha
    ON evaluaciones_postulacion(postulacion_id, creado_en DESC);

CREATE INDEX IF NOT EXISTS indice_evaluaciones_analisis
    ON evaluaciones_postulacion(analisis_cv_id);

CREATE UNIQUE INDEX IF NOT EXISTS indice_evaluacion_vigente_postulacion
    ON evaluaciones_postulacion(postulacion_id)
    WHERE vigente;

CREATE INDEX IF NOT EXISTS indice_evaluacion_compatibilidad_vigente
    ON evaluaciones_postulacion(porcentaje_compatibilidad DESC)
    WHERE vigente AND codigo_estado = 'COMPLETADO';

CREATE INDEX IF NOT EXISTS indice_resultados_requisito
    ON resultados_requisitos_evaluacion(requisito_id);
