-- Estados y registro persistente de ofertas laborales.

CREATE TABLE IF NOT EXISTS estados_oferta (
    codigo VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    es_final BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO estados_oferta (codigo, nombre, es_final) VALUES
    ('ENVIADA', 'Enviada', FALSE),
    ('ACEPTADA', 'Aceptada', TRUE),
    ('RECHAZADA', 'Rechazada', TRUE),
    ('VENCIDA', 'Vencida', TRUE),
    ('CANCELADA', 'Cancelada', TRUE)
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    es_final = EXCLUDED.es_final;

CREATE TABLE IF NOT EXISTS ofertas_laborales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id BIGINT NOT NULL
        REFERENCES postulaciones(id) ON DELETE CASCADE,
    creado_por_id BIGINT NOT NULL
        REFERENCES usuarios(id) ON DELETE RESTRICT,
    codigo_estado VARCHAR(20) NOT NULL DEFAULT 'ENVIADA'
        REFERENCES estados_oferta(codigo) ON DELETE RESTRICT,
    condiciones TEXT NOT NULL,
    vence_en TIMESTAMPTZ NOT NULL,
    enviada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    respondida_en TIMESTAMPTZ,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT verifica_oferta_condiciones
        CHECK (BTRIM(condiciones) <> ''),
    CONSTRAINT verifica_oferta_vencimiento
        CHECK (vence_en > enviada_en),
    CONSTRAINT verifica_oferta_respuesta_fecha
        CHECK (
            respondida_en IS NULL
            OR (respondida_en >= enviada_en AND respondida_en <= vence_en)
        ),
    CONSTRAINT verifica_oferta_estado_respuesta
        CHECK (
            (codigo_estado IN ('ACEPTADA', 'RECHAZADA') AND respondida_en IS NOT NULL)
            OR
            (codigo_estado IN ('ENVIADA', 'VENCIDA', 'CANCELADA') AND respondida_en IS NULL)
        ),
    CONSTRAINT verifica_oferta_actualizacion
        CHECK (enviada_en >= creado_en AND actualizado_en >= creado_en)
);

INSERT INTO tipos_notificacion (codigo, nombre) VALUES
    ('OFERTA_LABORAL', 'Oferta laboral'),
    ('RESPUESTA_OFERTA', 'Respuesta a oferta laboral')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre;

CREATE INDEX IF NOT EXISTS indice_ofertas_postulacion_fecha
    ON ofertas_laborales(postulacion_id, creado_en DESC);

CREATE INDEX IF NOT EXISTS indice_ofertas_creador
    ON ofertas_laborales(creado_por_id);

CREATE INDEX IF NOT EXISTS indice_ofertas_estado_vencimiento
    ON ofertas_laborales(codigo_estado, vence_en);

CREATE UNIQUE INDEX IF NOT EXISTS indice_oferta_activa_postulacion
    ON ofertas_laborales(postulacion_id)
    WHERE codigo_estado IN ('ENVIADA', 'ACEPTADA');
