ALTER TABLE perfiles_aspirantes
    ADD COLUMN IF NOT EXISTS profesion_texto VARCHAR(150),
    ADD COLUMN IF NOT EXISTS ciudad_texto VARCHAR(120);

ALTER TABLE experiencias_laborales
    ADD COLUMN IF NOT EXISTS profesion_texto VARCHAR(150),
    ADD COLUMN IF NOT EXISTS ciudad_texto VARCHAR(120);

ALTER TABLE formaciones_academicas
    ADD COLUMN IF NOT EXISTS institucion_texto VARCHAR(180),
    ADD COLUMN IF NOT EXISTS nivel_educativo_texto VARCHAR(100),
    ADD COLUMN IF NOT EXISTS area_estudio_texto VARCHAR(150);

ALTER TABLE habilidades_aspirantes
    ADD COLUMN IF NOT EXISTS habilidad_texto VARCHAR(150),
    ADD COLUMN IF NOT EXISTS nivel_habilidad_texto VARCHAR(80);

ALTER TABLE idiomas_aspirantes
    ADD COLUMN IF NOT EXISTS idioma_texto VARCHAR(80),
    ADD COLUMN IF NOT EXISTS nivel_idioma_texto VARCHAR(80);

ALTER TABLE certificaciones_aspirantes
    ADD COLUMN IF NOT EXISTS certificacion_texto VARCHAR(180),
    ADD COLUMN IF NOT EXISTS organizacion_emisora_texto VARCHAR(180);

UPDATE perfiles_aspirantes AS perfil
SET profesion_texto = profesion.nombre
FROM profesiones AS profesion
WHERE perfil.profesion_id = profesion.id
  AND NULLIF(BTRIM(perfil.profesion_texto), '') IS NULL;

UPDATE perfiles_aspirantes AS perfil
SET ciudad_texto = ciudad.nombre
FROM ciudades AS ciudad
WHERE perfil.ciudad_id = ciudad.id
  AND NULLIF(BTRIM(perfil.ciudad_texto), '') IS NULL;

UPDATE experiencias_laborales AS experiencia
SET profesion_texto = profesion.nombre
FROM profesiones AS profesion
WHERE experiencia.profesion_id = profesion.id
  AND NULLIF(BTRIM(experiencia.profesion_texto), '') IS NULL;

UPDATE experiencias_laborales AS experiencia
SET ciudad_texto = ciudad.nombre
FROM ciudades AS ciudad
WHERE experiencia.ciudad_id = ciudad.id
  AND NULLIF(BTRIM(experiencia.ciudad_texto), '') IS NULL;

UPDATE formaciones_academicas AS formacion
SET institucion_texto = institucion.nombre
FROM instituciones AS institucion
WHERE formacion.institucion_id = institucion.id
  AND NULLIF(BTRIM(formacion.institucion_texto), '') IS NULL;

UPDATE formaciones_academicas AS formacion
SET nivel_educativo_texto = nivel.nombre
FROM niveles_educativos AS nivel
WHERE formacion.nivel_educativo_id = nivel.id
  AND NULLIF(BTRIM(formacion.nivel_educativo_texto), '') IS NULL;

UPDATE formaciones_academicas AS formacion
SET area_estudio_texto = area.nombre
FROM areas_estudio AS area
WHERE formacion.area_estudio_id = area.id
  AND NULLIF(BTRIM(formacion.area_estudio_texto), '') IS NULL;

UPDATE habilidades_aspirantes AS habilidad_aspirante
SET habilidad_texto = habilidad.nombre
FROM habilidades AS habilidad
WHERE habilidad_aspirante.habilidad_id = habilidad.id
  AND NULLIF(BTRIM(habilidad_aspirante.habilidad_texto), '') IS NULL;

UPDATE habilidades_aspirantes AS habilidad_aspirante
SET nivel_habilidad_texto = nivel.nombre
FROM niveles_habilidad AS nivel
WHERE habilidad_aspirante.nivel_habilidad_id = nivel.id
  AND NULLIF(BTRIM(habilidad_aspirante.nivel_habilidad_texto), '') IS NULL;

UPDATE idiomas_aspirantes AS idioma_aspirante
SET idioma_texto = idioma.nombre
FROM idiomas AS idioma
WHERE idioma_aspirante.idioma_id = idioma.id
  AND NULLIF(BTRIM(idioma_aspirante.idioma_texto), '') IS NULL;

UPDATE idiomas_aspirantes AS idioma_aspirante
SET nivel_idioma_texto = nivel.nombre
FROM niveles_idioma AS nivel
WHERE idioma_aspirante.nivel_idioma_id = nivel.id
  AND NULLIF(BTRIM(idioma_aspirante.nivel_idioma_texto), '') IS NULL;

UPDATE certificaciones_aspirantes AS certificacion_aspirante
SET certificacion_texto = certificacion.nombre,
    organizacion_emisora_texto = certificacion.organizacion_emisora
FROM certificaciones AS certificacion
WHERE certificacion_aspirante.certificacion_id = certificacion.id
  AND (
      NULLIF(BTRIM(certificacion_aspirante.certificacion_texto), '') IS NULL
      OR NULLIF(BTRIM(certificacion_aspirante.organizacion_emisora_texto), '') IS NULL
  );

ALTER TABLE habilidades_aspirantes
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE idiomas_aspirantes
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE habilidades_aspirantes
    DROP CONSTRAINT IF EXISTS pk_habilidades_aspirantes_1;

ALTER TABLE habilidades_aspirantes
    DROP CONSTRAINT IF EXISTS pk_habilidades_aspirantes_id;

ALTER TABLE habilidades_aspirantes
    ADD CONSTRAINT pk_habilidades_aspirantes_id PRIMARY KEY (id);

ALTER TABLE idiomas_aspirantes
    DROP CONSTRAINT IF EXISTS pk_idiomas_aspirantes_1;

ALTER TABLE idiomas_aspirantes
    DROP CONSTRAINT IF EXISTS pk_idiomas_aspirantes_id;

ALTER TABLE idiomas_aspirantes
    ADD CONSTRAINT pk_idiomas_aspirantes_id PRIMARY KEY (id);

ALTER TABLE formaciones_academicas
    ALTER COLUMN institucion_id DROP NOT NULL,
    ALTER COLUMN nivel_educativo_id DROP NOT NULL;

ALTER TABLE habilidades_aspirantes
    ALTER COLUMN habilidad_id DROP NOT NULL;

ALTER TABLE idiomas_aspirantes
    ALTER COLUMN idioma_id DROP NOT NULL,
    ALTER COLUMN nivel_idioma_id DROP NOT NULL;

ALTER TABLE certificaciones_aspirantes
    ALTER COLUMN certificacion_id DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS indice_unico_habilidades_aspirantes_texto
    ON habilidades_aspirantes(aspirante_id, LOWER(BTRIM(habilidad_texto)))
    WHERE habilidad_texto IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS indice_unico_idiomas_aspirantes_texto
    ON idiomas_aspirantes(aspirante_id, LOWER(BTRIM(idioma_texto)))
    WHERE idioma_texto IS NOT NULL;

CREATE INDEX IF NOT EXISTS indice_habilidades_aspirantes_aspirante
    ON habilidades_aspirantes(aspirante_id);

CREATE INDEX IF NOT EXISTS indice_idiomas_aspirantes_aspirante
    ON idiomas_aspirantes(aspirante_id);

CREATE INDEX IF NOT EXISTS indice_perfiles_aspirantes_profesion_texto
    ON perfiles_aspirantes(profesion_texto);

CREATE INDEX IF NOT EXISTS indice_perfiles_aspirantes_ciudad_texto
    ON perfiles_aspirantes(ciudad_texto);

CREATE INDEX IF NOT EXISTS indice_experiencias_laborales_profesion_texto
    ON experiencias_laborales(profesion_texto);

CREATE INDEX IF NOT EXISTS indice_experiencias_laborales_ciudad_texto
    ON experiencias_laborales(ciudad_texto);
