-- PostgreSQL 14+
-- Sistema de reclutamiento y analisis inteligente de curriculum vitae.
-- Esquema relacional normalizado hasta tercera forma normal (3FN).

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE countries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_code        CHAR(2) NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE regions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id      BIGINT NOT NULL REFERENCES countries(id) ON DELETE RESTRICT,
    name            VARCHAR(100) NOT NULL,
    code            VARCHAR(20),
    UNIQUE (country_id, name),
    UNIQUE (country_id, code)
);

CREATE TABLE cities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id       BIGINT NOT NULL REFERENCES regions(id) ON DELETE RESTRICT,
    name            VARCHAR(120) NOT NULL,
    UNIQUE (region_id, name)
);

CREATE TABLE departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL UNIQUE,
    description     TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE occupations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE education_levels (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL UNIQUE,
    rank_order      SMALLINT NOT NULL UNIQUE CHECK (rank_order > 0)
);

CREATE TABLE fields_of_study (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE institutions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(180) NOT NULL,
    city_id         BIGINT REFERENCES cities(id) ON DELETE SET NULL,
    UNIQUE (name, city_id)
);

CREATE TABLE skill_categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE skills (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT REFERENCES skill_categories(id) ON DELETE SET NULL,
    name            CITEXT NOT NULL UNIQUE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE skill_levels (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE,
    rank_order      SMALLINT NOT NULL UNIQUE CHECK (rank_order > 0)
);

CREATE TABLE languages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_code        VARCHAR(10) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE language_levels (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(10) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE,
    rank_order      SMALLINT NOT NULL UNIQUE CHECK (rank_order > 0)
);

CREATE TABLE certifications (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(180) NOT NULL,
    issuing_organization    VARCHAR(180) NOT NULL,
    UNIQUE (name, issuing_organization)
);

CREATE TABLE employment_types (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE work_modes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE salary_periods (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(20) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE storage_providers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30) NOT NULL UNIQUE,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           CITEXT NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (email::TEXT ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);

CREATE TABLE user_roles (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id         BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE candidate_profiles (
    user_id                 BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    occupation_id           BIGINT REFERENCES occupations(id) ON DELETE SET NULL,
    city_id                 BIGINT REFERENCES cities(id) ON DELETE SET NULL,
    phone                   VARCHAR(30),
    address_line            VARCHAR(200),
    professional_summary    TEXT,
    available_from          DATE,
    willing_to_relocate     BOOLEAN NOT NULL DEFAULT FALSE,
    willing_to_travel       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE staff_profiles (
    user_id         BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    department_id   BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    job_title       VARCHAR(120),
    phone           VARCHAR(30)
);

CREATE TABLE candidate_experiences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id    BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    occupation_id   BIGINT REFERENCES occupations(id) ON DELETE SET NULL,
    company_name    VARCHAR(180) NOT NULL,
    position_title  VARCHAR(180) NOT NULL,
    city_id         BIGINT REFERENCES cities(id) ON DELETE SET NULL,
    start_date      DATE NOT NULL,
    end_date        DATE,
    description     TEXT,
    CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE candidate_educations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id        BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    institution_id      BIGINT NOT NULL REFERENCES institutions(id) ON DELETE RESTRICT,
    education_level_id  BIGINT NOT NULL REFERENCES education_levels(id) ON DELETE RESTRICT,
    field_of_study_id   BIGINT REFERENCES fields_of_study(id) ON DELETE SET NULL,
    degree_name         VARCHAR(180) NOT NULL,
    start_date          DATE,
    end_date            DATE,
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE candidate_skills (
    candidate_id        BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    skill_id            BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
    skill_level_id      BIGINT REFERENCES skill_levels(id) ON DELETE SET NULL,
    years_experience    NUMERIC(4,1) CHECK (years_experience >= 0),
    PRIMARY KEY (candidate_id, skill_id)
);

CREATE TABLE candidate_languages (
    candidate_id        BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    language_id         BIGINT NOT NULL REFERENCES languages(id) ON DELETE RESTRICT,
    language_level_id   BIGINT NOT NULL REFERENCES language_levels(id) ON DELETE RESTRICT,
    PRIMARY KEY (candidate_id, language_id)
);

CREATE TABLE candidate_certifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id        BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    certification_id    BIGINT NOT NULL REFERENCES certifications(id) ON DELETE RESTRICT,
    credential_code     VARCHAR(120),
    credential_url      TEXT,
    issued_on           DATE,
    expires_on          DATE,
    CHECK (expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on),
    UNIQUE (candidate_id, certification_id, credential_code)
);

CREATE TABLE vacancy_statuses (
    code            VARCHAR(20) PRIMARY KEY,
    name            VARCHAR(80) NOT NULL UNIQUE,
    is_terminal     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE vacancies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id       BIGINT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
    occupation_id       BIGINT REFERENCES occupations(id) ON DELETE SET NULL,
    created_by_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    city_id             BIGINT REFERENCES cities(id) ON DELETE SET NULL,
    employment_type_id  BIGINT NOT NULL REFERENCES employment_types(id) ON DELETE RESTRICT,
    work_mode_id        BIGINT NOT NULL REFERENCES work_modes(id) ON DELETE RESTRICT,
    salary_period_id    BIGINT REFERENCES salary_periods(id) ON DELETE RESTRICT,
    status_code         VARCHAR(20) NOT NULL DEFAULT 'DRAFT' REFERENCES vacancy_statuses(code) ON DELETE RESTRICT,
    title               VARCHAR(180) NOT NULL,
    description         TEXT NOT NULL,
    location_detail     VARCHAR(200),
    salary_min          NUMERIC(14,2),
    salary_max          NUMERIC(14,2),
    currency_code       CHAR(3),
    openings_count      INTEGER NOT NULL DEFAULT 1 CHECK (openings_count > 0),
    published_at        TIMESTAMPTZ,
    closes_at           TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (salary_min IS NULL OR salary_min >= 0),
    CHECK (salary_max IS NULL OR salary_max >= 0),
    CHECK (salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min),
    CHECK (
        (salary_min IS NULL AND salary_max IS NULL AND currency_code IS NULL AND salary_period_id IS NULL)
        OR (currency_code IS NOT NULL AND salary_period_id IS NOT NULL)
    ),
    CHECK (closes_at IS NULL OR published_at IS NULL OR closes_at > published_at)
);

CREATE TABLE vacancy_status_history (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id              BIGINT NOT NULL REFERENCES vacancies(id) ON DELETE CASCADE,
    previous_status_code    VARCHAR(20) REFERENCES vacancy_statuses(code) ON DELETE RESTRICT,
    new_status_code         VARCHAR(20) NOT NULL REFERENCES vacancy_statuses(code) ON DELETE RESTRICT,
    changed_by_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    reason                  TEXT,
    changed_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (previous_status_code IS NULL OR previous_status_code <> new_status_code)
);

CREATE TABLE requirement_kinds (
    code            VARCHAR(30) PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE vacancy_requirements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id      BIGINT NOT NULL REFERENCES vacancies(id) ON DELETE CASCADE,
    kind_code       VARCHAR(30) NOT NULL REFERENCES requirement_kinds(code) ON DELETE RESTRICT,
    description     TEXT,
    is_mandatory    BOOLEAN NOT NULL DEFAULT TRUE,
    weight          NUMERIC(5,2) NOT NULL CHECK (weight > 0 AND weight <= 100),
    display_order   SMALLINT NOT NULL DEFAULT 1 CHECK (display_order > 0),
    UNIQUE (vacancy_id, display_order)
);

CREATE TABLE vacancy_skill_requirements (
    requirement_id      BIGINT PRIMARY KEY REFERENCES vacancy_requirements(id) ON DELETE CASCADE,
    skill_id            BIGINT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
    min_skill_level_id  BIGINT REFERENCES skill_levels(id) ON DELETE RESTRICT,
    min_years           NUMERIC(4,1) CHECK (min_years >= 0)
);

CREATE TABLE vacancy_language_requirements (
    requirement_id          BIGINT PRIMARY KEY REFERENCES vacancy_requirements(id) ON DELETE CASCADE,
    language_id             BIGINT NOT NULL REFERENCES languages(id) ON DELETE RESTRICT,
    min_language_level_id   BIGINT NOT NULL REFERENCES language_levels(id) ON DELETE RESTRICT
);

CREATE TABLE vacancy_certification_requirements (
    requirement_id      BIGINT PRIMARY KEY REFERENCES vacancy_requirements(id) ON DELETE CASCADE,
    certification_id    BIGINT NOT NULL REFERENCES certifications(id) ON DELETE RESTRICT,
    must_be_valid       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE vacancy_education_requirements (
    requirement_id          BIGINT PRIMARY KEY REFERENCES vacancy_requirements(id) ON DELETE CASCADE,
    min_education_level_id  BIGINT NOT NULL REFERENCES education_levels(id) ON DELETE RESTRICT,
    field_of_study_id       BIGINT REFERENCES fields_of_study(id) ON DELETE RESTRICT
);

CREATE TABLE vacancy_experience_requirements (
    requirement_id      BIGINT PRIMARY KEY REFERENCES vacancy_requirements(id) ON DELETE CASCADE,
    occupation_id       BIGINT REFERENCES occupations(id) ON DELETE RESTRICT,
    min_months          INTEGER NOT NULL CHECK (min_months >= 0)
);

CREATE TABLE vacancy_availability_requirements (
    requirement_id          BIGINT PRIMARY KEY REFERENCES vacancy_requirements(id) ON DELETE CASCADE,
    required_from           DATE,
    relocation_required     BOOLEAN NOT NULL DEFAULT FALSE,
    travel_required         BOOLEAN NOT NULL DEFAULT FALSE,
    schedule_description    VARCHAR(200)
);

CREATE TABLE curricula (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id        BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    storage_provider_id BIGINT NOT NULL REFERENCES storage_providers(id) ON DELETE RESTRICT,
    object_key          VARCHAR(1024) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
    size_bytes          BIGINT NOT NULL CHECK (size_bytes > 0),
    checksum_sha256     CHAR(64) NOT NULL CHECK (checksum_sha256 ~ '^[0-9a-fA-F]{64}$'),
    duplicate_of_id     BIGINT REFERENCES curricula(id) ON DELETE SET NULL,
    uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (storage_provider_id, object_key),
    CHECK (duplicate_of_id IS NULL OR duplicate_of_id <> id)
);

CREATE TABLE ai_models (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider        VARCHAR(100) NOT NULL,
    name            VARCHAR(150) NOT NULL,
    version         VARCHAR(80) NOT NULL,
    UNIQUE (provider, name, version)
);

CREATE TABLE analysis_engines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_model_id     BIGINT REFERENCES ai_models(id) ON DELETE RESTRICT,
    name            VARCHAR(120) NOT NULL,
    version         VARCHAR(80) NOT NULL,
    prompt_version  VARCHAR(80),
    UNIQUE (name, version, prompt_version)
);

CREATE TABLE processing_statuses (
    code            VARCHAR(20) PRIMARY KEY,
    name            VARCHAR(80) NOT NULL UNIQUE,
    is_terminal     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE cv_analyses (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id                   BIGINT NOT NULL REFERENCES curricula(id) ON DELETE CASCADE,
    analysis_engine_id              BIGINT NOT NULL REFERENCES analysis_engines(id) ON DELETE RESTRICT,
    status_code                     VARCHAR(20) NOT NULL DEFAULT 'PENDING' REFERENCES processing_statuses(code) ON DELETE RESTRICT,
    extracted_text                  TEXT,
    professional_summary            TEXT,
    calculated_experience_months    INTEGER CHECK (calculated_experience_months >= 0),
    started_at                      TIMESTAMPTZ,
    completed_at                    TIMESTAMPTZ,
    error_message                   TEXT,
    is_current                      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE cv_analysis_personal_data (
    analysis_id         BIGINT PRIMARY KEY REFERENCES cv_analyses(id) ON DELETE CASCADE,
    full_name           VARCHAR(200),
    email               CITEXT,
    phone               VARCHAR(30),
    occupation_text     VARCHAR(180),
    city_text           VARCHAR(180)
);

CREATE TABLE cv_analysis_experiences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id     BIGINT NOT NULL REFERENCES cv_analyses(id) ON DELETE CASCADE,
    occupation_id   BIGINT REFERENCES occupations(id) ON DELETE SET NULL,
    company_name    VARCHAR(180),
    position_title  VARCHAR(180) NOT NULL,
    start_date      DATE,
    end_date        DATE,
    description     TEXT,
    confidence      NUMERIC(5,4) CHECK (confidence >= 0 AND confidence <= 1),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE cv_analysis_educations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT NOT NULL REFERENCES cv_analyses(id) ON DELETE CASCADE,
    institution_text    VARCHAR(180) NOT NULL,
    education_level_id  BIGINT REFERENCES education_levels(id) ON DELETE SET NULL,
    field_of_study_id   BIGINT REFERENCES fields_of_study(id) ON DELETE SET NULL,
    degree_name         VARCHAR(180),
    start_date          DATE,
    end_date            DATE,
    confidence          NUMERIC(5,4) CHECK (confidence >= 0 AND confidence <= 1),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE cv_analysis_skills (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id     BIGINT NOT NULL REFERENCES cv_analyses(id) ON DELETE CASCADE,
    skill_id        BIGINT REFERENCES skills(id) ON DELETE SET NULL,
    detected_name   VARCHAR(150) NOT NULL,
    confidence      NUMERIC(5,4) CHECK (confidence >= 0 AND confidence <= 1),
    evidence        TEXT,
    UNIQUE (analysis_id, detected_name)
);

CREATE TABLE cv_analysis_languages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT NOT NULL REFERENCES cv_analyses(id) ON DELETE CASCADE,
    language_id         BIGINT REFERENCES languages(id) ON DELETE SET NULL,
    detected_name       VARCHAR(80) NOT NULL,
    language_level_id   BIGINT REFERENCES language_levels(id) ON DELETE SET NULL,
    confidence          NUMERIC(5,4) CHECK (confidence >= 0 AND confidence <= 1),
    UNIQUE (analysis_id, detected_name)
);

CREATE TABLE cv_analysis_certifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT NOT NULL REFERENCES cv_analyses(id) ON DELETE CASCADE,
    certification_id    BIGINT REFERENCES certifications(id) ON DELETE SET NULL,
    detected_name       VARCHAR(180) NOT NULL,
    issued_on           DATE,
    expires_on          DATE,
    confidence          NUMERIC(5,4) CHECK (confidence >= 0 AND confidence <= 1),
    CHECK (expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on),
    UNIQUE (analysis_id, detected_name)
);

CREATE TABLE application_statuses (
    code            VARCHAR(30) PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    is_terminal     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE applications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id          BIGINT NOT NULL REFERENCES vacancies(id) ON DELETE RESTRICT,
    candidate_id        BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE RESTRICT,
    curriculum_id       BIGINT NOT NULL REFERENCES curricula(id) ON DELETE RESTRICT,
    status_code         VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED' REFERENCES application_statuses(code) ON DELETE RESTRICT,
    cover_letter        TEXT,
    applied_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    withdrawn_at        TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (vacancy_id, candidate_id),
    CHECK (withdrawn_at IS NULL OR withdrawn_at >= applied_at)
);

CREATE TABLE application_status_history (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id          BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    previous_status_code    VARCHAR(30) REFERENCES application_statuses(code) ON DELETE RESTRICT,
    new_status_code         VARCHAR(30) NOT NULL REFERENCES application_statuses(code) ON DELETE RESTRICT,
    changed_by_id           BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reason                  TEXT,
    changed_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (previous_status_code IS NULL OR previous_status_code <> new_status_code)
);

CREATE TABLE application_evaluations (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id              BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    cv_analysis_id              BIGINT NOT NULL REFERENCES cv_analyses(id) ON DELETE RESTRICT,
    analysis_engine_id          BIGINT NOT NULL REFERENCES analysis_engines(id) ON DELETE RESTRICT,
    status_code                 VARCHAR(20) NOT NULL DEFAULT 'PENDING' REFERENCES processing_statuses(code) ON DELETE RESTRICT,
    compatibility_percentage    NUMERIC(5,2) CHECK (compatibility_percentage >= 0 AND compatibility_percentage <= 100),
    strengths                   TEXT,
    improvement_recommendations TEXT,
    started_at                  TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    error_message               TEXT,
    is_current                  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE evaluation_requirement_results (
    evaluation_id       BIGINT NOT NULL REFERENCES application_evaluations(id) ON DELETE CASCADE,
    requirement_id      BIGINT NOT NULL REFERENCES vacancy_requirements(id) ON DELETE RESTRICT,
    is_met              BOOLEAN NOT NULL,
    score_percentage    NUMERIC(5,2) NOT NULL CHECK (score_percentage >= 0 AND score_percentage <= 100),
    evidence            TEXT,
    explanation         TEXT,
    PRIMARY KEY (evaluation_id, requirement_id)
);

CREATE TABLE interview_statuses (
    code            VARCHAR(20) PRIMARY KEY,
    name            VARCHAR(80) NOT NULL UNIQUE,
    is_terminal     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE interviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id      BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    created_by_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status_code         VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' REFERENCES interview_statuses(code) ON DELETE RESTRICT,
    starts_at           TIMESTAMPTZ NOT NULL,
    ends_at             TIMESTAMPTZ NOT NULL,
    timezone_name       VARCHAR(80) NOT NULL,
    location_detail     VARCHAR(200),
    meeting_url         TEXT,
    notes               TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (ends_at > starts_at),
    CHECK (location_detail IS NOT NULL OR meeting_url IS NOT NULL)
);

CREATE TABLE notification_types (
    code            VARCHAR(40) PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE notification_channels (
    code            VARCHAR(20) PRIMARY KEY,
    name            VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE delivery_statuses (
    code            VARCHAR(20) PRIMARY KEY,
    name            VARCHAR(80) NOT NULL UNIQUE,
    is_terminal     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE notifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type_code           VARCHAR(40) NOT NULL REFERENCES notification_types(code) ON DELETE RESTRICT,
    application_id      BIGINT REFERENCES applications(id) ON DELETE CASCADE,
    interview_id        BIGINT REFERENCES interviews(id) ON DELETE CASCADE,
    title               VARCHAR(180) NOT NULL,
    message             TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at             TIMESTAMPTZ,
    CHECK (read_at IS NULL OR read_at >= created_at)
);

CREATE TABLE notification_deliveries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id     BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    channel_code        VARCHAR(20) NOT NULL REFERENCES notification_channels(code) ON DELETE RESTRICT,
    status_code         VARCHAR(20) NOT NULL DEFAULT 'PENDING' REFERENCES delivery_statuses(code) ON DELETE RESTRICT,
    recipient_address   VARCHAR(320),
    scheduled_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sent_at             TIMESTAMPTZ,
    provider_message_id VARCHAR(255),
    UNIQUE (notification_id, channel_code),
    CHECK (sent_at IS NULL OR sent_at >= scheduled_at)
);

CREATE TABLE notification_delivery_attempts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id     BIGINT NOT NULL REFERENCES notification_deliveries(id) ON DELETE CASCADE,
    attempted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    succeeded       BOOLEAN NOT NULL,
    error_message   TEXT
);

-- Datos de catalogo minimos para los flujos principales.
INSERT INTO roles (code, name) VALUES
    ('CANDIDATE', 'Aspirante'),
    ('HR', 'Recursos Humanos'),
    ('ADMIN', 'Administrador');

INSERT INTO vacancy_statuses (code, name, is_terminal) VALUES
    ('DRAFT', 'Pendiente', FALSE),
    ('PUBLISHED', 'Activa', FALSE),
    ('PAUSED', 'Pausada', FALSE),
    ('CLOSED', 'Cerrada', TRUE);

INSERT INTO application_statuses (code, name, is_terminal) VALUES
    ('SUBMITTED', 'Enviada', FALSE),
    ('UNDER_REVIEW', 'En revision', FALSE),
    ('SHORTLISTED', 'Preseleccionada', FALSE),
    ('INTERVIEW', 'Entrevista', FALSE),
    ('OFFERED', 'Oferta enviada', FALSE),
    ('HIRED', 'Contratada', TRUE),
    ('REJECTED', 'Rechazada', TRUE),
    ('WITHDRAWN', 'Retirada', TRUE);

INSERT INTO processing_statuses (code, name, is_terminal) VALUES
    ('PENDING', 'Pendiente', FALSE),
    ('PROCESSING', 'Procesando', FALSE),
    ('COMPLETED', 'Completado', TRUE),
    ('FAILED', 'Fallido', TRUE);

INSERT INTO requirement_kinds (code, name) VALUES
    ('SKILL', 'Habilidad'),
    ('LANGUAGE', 'Idioma'),
    ('CERTIFICATION', 'Certificacion'),
    ('EDUCATION', 'Educacion'),
    ('EXPERIENCE', 'Experiencia'),
    ('AVAILABILITY', 'Disponibilidad');

INSERT INTO interview_statuses (code, name, is_terminal) VALUES
    ('SCHEDULED', 'Programada', FALSE),
    ('CONFIRMED', 'Confirmada', FALSE),
    ('COMPLETED', 'Completada', TRUE),
    ('CANCELLED', 'Cancelada', TRUE),
    ('NO_SHOW', 'No asistio', TRUE);

INSERT INTO notification_types (code, name) VALUES
    ('APPLICATION_CONFIRMATION', 'Confirmacion de postulacion'),
    ('STATUS_CHANGED', 'Cambio de estado'),
    ('INTERVIEW_INVITATION', 'Invitacion a entrevista');

INSERT INTO notification_channels (code, name) VALUES
    ('IN_APP', 'Aplicacion'),
    ('EMAIL', 'Correo electronico');

INSERT INTO delivery_statuses (code, name, is_terminal) VALUES
    ('PENDING', 'Pendiente', FALSE),
    ('PROCESSING', 'Procesando', FALSE),
    ('SENT', 'Enviado', TRUE),
    ('FAILED', 'Fallido', TRUE);

INSERT INTO storage_providers (code, name) VALUES
    ('S3', 'Amazon S3'),
    ('AZURE_BLOB', 'Azure Blob Storage'),
    ('BACKBLAZE_B2', 'Backblaze B2 privado');

INSERT INTO skill_levels (code, name, rank_order) VALUES
    ('BASIC', 'Basico', 1),
    ('INTERMEDIATE', 'Intermedio', 2),
    ('ADVANCED', 'Avanzado', 3),
    ('EXPERT', 'Experto', 4);

INSERT INTO language_levels (code, name, rank_order) VALUES
    ('A1', 'Principiante', 1),
    ('A2', 'Elemental', 2),
    ('B1', 'Intermedio', 3),
    ('B2', 'Intermedio alto', 4),
    ('C1', 'Avanzado', 5),
    ('C2', 'Dominio', 6),
    ('NATIVE', 'Nativo', 7);

-- Indices de claves foraneas y consultas operativas.
CREATE INDEX idx_regions_country ON regions(country_id);
CREATE INDEX idx_cities_region ON cities(region_id);
CREATE INDEX idx_institutions_city ON institutions(city_id);
CREATE INDEX idx_skills_category ON skills(category_id);
CREATE INDEX idx_user_roles_role ON user_roles(role_id);
CREATE INDEX idx_candidate_profiles_occupation ON candidate_profiles(occupation_id);
CREATE INDEX idx_candidate_profiles_city ON candidate_profiles(city_id);
CREATE INDEX idx_staff_profiles_department ON staff_profiles(department_id);
CREATE INDEX idx_candidate_experiences_candidate ON candidate_experiences(candidate_id);
CREATE INDEX idx_candidate_experiences_occupation ON candidate_experiences(occupation_id);
CREATE INDEX idx_candidate_experiences_city ON candidate_experiences(city_id);
CREATE INDEX idx_candidate_educations_candidate ON candidate_educations(candidate_id);
CREATE INDEX idx_candidate_educations_institution ON candidate_educations(institution_id);
CREATE INDEX idx_candidate_educations_level ON candidate_educations(education_level_id);
CREATE INDEX idx_candidate_educations_field ON candidate_educations(field_of_study_id);
CREATE INDEX idx_candidate_skills_skill ON candidate_skills(skill_id);
CREATE INDEX idx_candidate_languages_language ON candidate_languages(language_id);
CREATE INDEX idx_candidate_certifications_candidate ON candidate_certifications(candidate_id);
CREATE INDEX idx_candidate_certifications_catalog ON candidate_certifications(certification_id);
CREATE INDEX idx_vacancies_department ON vacancies(department_id);
CREATE INDEX idx_vacancies_occupation ON vacancies(occupation_id);
CREATE INDEX idx_vacancies_created_by ON vacancies(created_by_id);
CREATE INDEX idx_vacancies_city ON vacancies(city_id);
CREATE INDEX idx_vacancies_employment_type ON vacancies(employment_type_id);
CREATE INDEX idx_vacancies_work_mode ON vacancies(work_mode_id);
CREATE INDEX idx_vacancies_status ON vacancies(status_code);
CREATE INDEX idx_vacancy_status_history_vacancy_date ON vacancy_status_history(vacancy_id, changed_at DESC);
CREATE INDEX idx_vacancy_requirements_vacancy ON vacancy_requirements(vacancy_id);
CREATE INDEX idx_vacancy_requirements_kind ON vacancy_requirements(kind_code);
CREATE INDEX idx_vacancy_skill_req_skill ON vacancy_skill_requirements(skill_id);
CREATE INDEX idx_vacancy_language_req_language ON vacancy_language_requirements(language_id);
CREATE INDEX idx_vacancy_cert_req_certification ON vacancy_certification_requirements(certification_id);
CREATE INDEX idx_curricula_candidate_date ON curricula(candidate_id, uploaded_at DESC);
CREATE INDEX idx_curricula_checksum ON curricula(checksum_sha256);
CREATE INDEX idx_curricula_duplicate ON curricula(duplicate_of_id) WHERE duplicate_of_id IS NOT NULL;
CREATE INDEX idx_analysis_engines_model ON analysis_engines(ai_model_id);
CREATE INDEX idx_cv_analyses_curriculum_date ON cv_analyses(curriculum_id, created_at DESC);
CREATE INDEX idx_cv_analyses_engine ON cv_analyses(analysis_engine_id);
CREATE UNIQUE INDEX uq_cv_analyses_current ON cv_analyses(curriculum_id) WHERE is_current;
CREATE INDEX idx_cv_analysis_experiences_analysis ON cv_analysis_experiences(analysis_id);
CREATE INDEX idx_cv_analysis_experiences_occupation ON cv_analysis_experiences(occupation_id);
CREATE INDEX idx_cv_analysis_educations_analysis ON cv_analysis_educations(analysis_id);
CREATE INDEX idx_cv_analysis_skills_analysis ON cv_analysis_skills(analysis_id);
CREATE INDEX idx_cv_analysis_skills_skill ON cv_analysis_skills(skill_id) WHERE skill_id IS NOT NULL;
CREATE INDEX idx_cv_analysis_languages_analysis ON cv_analysis_languages(analysis_id);
CREATE INDEX idx_cv_analysis_certifications_analysis ON cv_analysis_certifications(analysis_id);
CREATE INDEX idx_applications_candidate_date ON applications(candidate_id, applied_at DESC);
CREATE INDEX idx_applications_vacancy_status_date ON applications(vacancy_id, status_code, applied_at DESC);
CREATE INDEX idx_application_history_application_date ON application_status_history(application_id, changed_at DESC);
CREATE INDEX idx_application_history_changed_by ON application_status_history(changed_by_id);
CREATE INDEX idx_evaluations_application_date ON application_evaluations(application_id, created_at DESC);
CREATE INDEX idx_evaluations_cv_analysis ON application_evaluations(cv_analysis_id);
CREATE UNIQUE INDEX uq_evaluations_current ON application_evaluations(application_id) WHERE is_current;
CREATE INDEX idx_current_evaluation_compatibility ON application_evaluations(compatibility_percentage DESC) WHERE is_current AND status_code = 'COMPLETED';
CREATE INDEX idx_evaluation_results_requirement ON evaluation_requirement_results(requirement_id);
CREATE INDEX idx_interviews_application_date ON interviews(application_id, starts_at);
CREATE INDEX idx_interviews_created_by ON interviews(created_by_id);
CREATE INDEX idx_notifications_recipient_date ON notifications(recipient_user_id, created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(recipient_user_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX idx_notifications_application ON notifications(application_id) WHERE application_id IS NOT NULL;
CREATE INDEX idx_notifications_interview ON notifications(interview_id) WHERE interview_id IS NOT NULL;
CREATE INDEX idx_deliveries_status_schedule ON notification_deliveries(status_code, scheduled_at);
CREATE INDEX idx_delivery_attempts_delivery_date ON notification_delivery_attempts(delivery_id, attempted_at DESC);

-- Busquedas por nombre, profesion, empresa y puesto.
CREATE INDEX idx_users_first_name_trgm ON users USING GIN (first_name gin_trgm_ops);
CREATE INDEX idx_users_last_name_trgm ON users USING GIN (last_name gin_trgm_ops);
CREATE INDEX idx_occupations_name_trgm ON occupations USING GIN (name gin_trgm_ops);
CREATE INDEX idx_skills_name_trgm ON skills USING GIN ((name::TEXT) gin_trgm_ops);
CREATE INDEX idx_experiences_company_trgm ON candidate_experiences USING GIN (company_name gin_trgm_ops);
CREATE INDEX idx_experiences_position_trgm ON candidate_experiences USING GIN (position_title gin_trgm_ops);

-- Las plazas publicadas son la consulta principal del portal del aspirante.
CREATE INDEX idx_vacancies_published_closing
    ON vacancies(closes_at, published_at DESC)
    WHERE status_code = 'PUBLISHED';

COMMIT;
