from django.urls import path

from hello.views import (
    analisis,
    agregar_habilidad,
    agregar_idioma,
    aspirantes,
    cargar_curriculo,
    cambiar_contrasena,
    cambiar_estado_entrevista,
    cambiar_estado_postulacion,
    cambiar_estado_plaza,
    cerrar_sesion,
    configuracion,
    dashboard,
    descargar_curriculo,
    detalle_oportunidad,
    detalle_postulacion,
    detalle_plaza,
    editar_registro_perfil,
    editar_plaza,
    eliminar_habilidad,
    eliminar_idioma,
    eliminar_registro_perfil,
    exportar_reporte,
    index,
    mi_postulacion,
    mis_postulaciones,
    nueva_plaza,
    oportunidades,
    perfil_aspirante,
    plazas,
    portal,
    postulaciones,
    programar_entrevista,
    reportes,
    reenviar_verificacion,
    registrar_aspirante,
    restablecer_contrasena,
    salud,
    solicitar_recuperacion,
    retirar_postulacion,
    verificar_correo,
)

urlpatterns = [
    path("", index, name="index"),
    path("dashboard/", dashboard, name="dashboard"),
    path("plazas/", plazas, name="plazas"),
    path("plazas/nueva/", nueva_plaza, name="nueva_plaza"),
    path("plazas/<int:plaza_id>/", detalle_plaza, name="detalle_plaza"),
    path("plazas/<int:plaza_id>/editar/", editar_plaza, name="editar_plaza"),
    path(
        "plazas/<int:plaza_id>/estado/<str:estado>/",
        cambiar_estado_plaza,
        name="cambiar_estado_plaza",
    ),
    path("aspirantes/", aspirantes, name="aspirantes"),
    path("postulaciones/", postulaciones, name="postulaciones"),
    path(
        "postulaciones/<int:postulacion_id>/",
        detalle_postulacion,
        name="detalle_postulacion",
    ),
    path(
        "postulaciones/<int:postulacion_id>/estado/",
        cambiar_estado_postulacion,
        name="cambiar_estado_postulacion",
    ),
    path(
        "postulaciones/<int:postulacion_id>/entrevista/",
        programar_entrevista,
        name="programar_entrevista",
    ),
    path(
        "entrevistas/<int:entrevista_id>/estado/",
        cambiar_estado_entrevista,
        name="cambiar_estado_entrevista",
    ),
    path("analisis/", analisis, name="analisis"),
    path("reportes/", reportes, name="reportes"),
    path("reportes/exportar.csv", exportar_reporte, name="exportar_reporte"),
    path("configuracion/", configuracion, name="configuracion"),
    path("portal/", portal, name="portal"),
    path("portal/perfil/", perfil_aspirante, name="perfil_aspirante"),
    path("portal/perfil/habilidades/nueva/", agregar_habilidad, name="agregar_habilidad"),
    path(
        "portal/perfil/habilidades/<int:habilidad_id>/eliminar/",
        eliminar_habilidad,
        name="eliminar_habilidad",
    ),
    path("portal/perfil/idiomas/nuevo/", agregar_idioma, name="agregar_idioma"),
    path(
        "portal/perfil/idiomas/<int:idioma_id>/eliminar/",
        eliminar_idioma,
        name="eliminar_idioma",
    ),
    path(
        "portal/perfil/<str:tipo>/nuevo/",
        editar_registro_perfil,
        name="nuevo_registro_perfil",
    ),
    path(
        "portal/perfil/<str:tipo>/<int:registro_id>/editar/",
        editar_registro_perfil,
        name="editar_registro_perfil",
    ),
    path(
        "portal/perfil/<str:tipo>/<int:registro_id>/eliminar/",
        eliminar_registro_perfil,
        name="eliminar_registro_perfil",
    ),
    path("portal/curriculo/cargar/", cargar_curriculo, name="cargar_curriculo"),
    path(
        "curriculos/<int:curriculo_id>/descargar/",
        descargar_curriculo,
        name="descargar_curriculo",
    ),
    path("portal/oportunidades/", oportunidades, name="oportunidades"),
    path(
        "portal/oportunidades/<int:plaza_id>/",
        detalle_oportunidad,
        name="detalle_oportunidad",
    ),
    path("portal/postulaciones/", mis_postulaciones, name="mis_postulaciones"),
    path(
        "portal/postulaciones/<int:postulacion_id>/",
        mi_postulacion,
        name="mi_postulacion",
    ),
    path(
        "portal/postulaciones/<int:postulacion_id>/retirar/",
        retirar_postulacion,
        name="retirar_postulacion",
    ),
    path("cuenta/registro/", registrar_aspirante, name="registrar_aspirante"),
    path(
        "cuenta/reenviar-verificacion/",
        reenviar_verificacion,
        name="reenviar_verificacion",
    ),
    path("cuenta/salir/", cerrar_sesion, name="cerrar_sesion"),
    path(
        "cuenta/cambiar-contrasena/",
        cambiar_contrasena,
        name="cambiar_contrasena",
    ),
    path(
        "cuenta/recuperar/",
        solicitar_recuperacion,
        name="solicitar_recuperacion",
    ),
    path(
        "cuenta/restablecer/<uidb64>/<token>/",
        restablecer_contrasena,
        name="restablecer_contrasena",
    ),
    path(
        "cuenta/verificar/<uidb64>/<token>/",
        verificar_correo,
        name="verificar_correo",
    ),
    path("salud/", salud, name="salud"),
]
